#!/bin/bash

## Description: Joue les migrations Prisma en mode développement
## Usage: migrate [flags]
## Example: "ddev migrate" ou "ddev migrate --name add_something"

cd /var/www/html
exec yarn workspace confiture-rest-api run migrate:dev "$@"
